### ISSUE TITLE
Header detection depends on LF

### ISSUE THREAD

**Issue by tivac** [javascript-studio/studio-changes#1]
https://github.com/javascript-studio/studio-changes/blob/b32a534b58ee8b271d043962ee7f2c78852a8501/lib/changes.js#L12

Means that if you're on windows and the file is automatically checked out with CRLF changes will fail with a `Unexpected CHANGES.md file header` message.

Hopefully a small fix, for now I've forced the file to use LF but that isn't ideal IMO.

**Comment by mantoni** [comment]
Oh, yes. Good catch. Also potentially [here](https://github.com/javascript-studio/studio-changes/blob/b32a534b58ee8b271d043962ee7f2c78852a8501/lib/changes.js#L15). Will look into it.
