### ISSUE TITLE
Failing to install the latest version: @studio/editor is not published

### ISSUE THREAD

**Issue by kasperlewau** [javascript-studio/studio-changes#19]
I can't seem to find any published version of `@studio/editor` on registry.npmjs.org. 

Hitting the `@studio/editor` button at https://www.npmjs.com/package/@studio/changes?activeTab=dependencies takes me to this page: 

https://www.npmjs.com/login?next=/package/@studio%2Feditor

--- 

Pinning the `@studio/changes` version to `<1.4.2` across our repos sorts out `npm install`.

**Comment by mantoni** [comment]
I'm very sorry. The package was published but marked as private by default. I changed to scope to public which should sort out your installs.

Thanks for raising! 👍

**Comment by kasperlewau** [comment]
Beautiful! Thanks for the swift turnaround :heart:
