### ISSUE TITLE
Falls back to Notepad when used with Cmder

### ISSUE THREAD

**Issue by TekSiDoT** [javascript-studio/studio-changes#3]
During versioning, the CHANGES.md gets opened with notepad instead of the associated program (VS Code).

Calling CHANGES.md from the respective command line however, shows the correct behavior and respects the system-wide .md file association.

System: Windows 10
Cmder: 161206 stable

**Comment by crookedneighbor** [comment]
This module uses [editor](https://www.npmjs.com/package/editor) to open your preferred editor. By default, on Windows, it [uses Notepad](https://github.com/substack/node-editor/blob/15200af2c417c65a4df153f39f32143dcd476375/index.js#L10). If you have VISUAL or EDITOR env variables set, it'll [use that instead](https://github.com/substack/node-editor/blob/15200af2c417c65a4df153f39f32143dcd476375/index.js#L11).

So, this is not a problem with this module (or the editor module).

**Comment by mantoni** [comment]
Thanks @crookedneighbor. This is how to solve it. Can this be closed then @TekSiDoT ?

**Comment by TekSiDoT** [comment]
Yes, thank you for your help!
