### ISSUE TITLE
Does not wait for editor to close

### ISSUE THREAD

**Issue by mroderick** [javascript-studio/studio-changes#30]
In working on the Sinon projects, I have more than once experienced an undesirable situation.

Allow me to elaborate:

* In https://github.com/sinonjs/samsam/blob/master/package.json#L29-L31, we are following the recommended setup
* My git editor is defined as `subl -n -w`, which instructs git to use Sublime Text, and wait for the file to be closed before continuing
* There's hardly anything in my `npm` config
    ```
    $ npm config list
    ; cli configs
    metrics-registry = "https://registry.npmjs.org/"
    scope = ""
    user-agent = "npm/6.13.7 node/v12.15.0 darwin x64"

    ; node bin location = /Users/morgan/.nvm/versions/node/v12.15.0/bin/node
    ; cwd = /Users/morgan/code/sinonjs/samsam
    ; HOME = /Users/morgan
    ; "npm config ls -l" to show all defaults.
    ```

#### Steps to reproduce

1. Use Sublime Text as your git editor
1. Make changes to `@sinonjs/samsam` (or another project configured with the recommended configuration)
1. `npm version patch`
1. Edit the changelog in the `CHANGES.md` that is opened in Sublime Text
1. Close the file
1. Observe that the package has already been published, and that your changes to `CHANGES.md` are unstaged

**Comment by mroderick** [comment]
I believe I found the solution:

```
# change this
export EDITOR='subl';

# to this
export EDITOR='subl -w -n';
```

This can be closed, as it was a misconfiguration of my environment

**Comment by mantoni** [comment]
Shall we add a note in the `README.md` on how to configure sublime?
