### ISSUE TITLE
Allow option to specify changelog filename

### ISSUE THREAD

**Issue by crookedneighbor** [javascript-studio/studio-changes#5]
Would be great to allow a command line argument to specify the filename. IE, something like:

```
$ changes --file-name "CHANGELOG.md"
```

**Comment by mantoni** [comment]
Makes sense. I'm busy now and away next week. If you have time to make a PR, that'd be great! Otherwise I'll look into this once I'm back. For this module, I'd prefer to use a minimal option parser, e.g. [minimist](https://www.npmjs.com/package/minimist).

**Comment by crookedneighbor** [comment]
:+1: was going to suggest something similar.
