### ISSUE TITLE
Does not wait for VS Code to return

### ISSUE THREAD

**Issue by TekSiDoT** [javascript-studio/studio-changes#7]
When using Visual Studio Code as the editor referenced in the EDITOR env variable, changes does not wait for VS Code to return. 

Changes made to CHANGES.md are thus not committed.

**Comment by mantoni** [comment]
If the command line call to VSC returns immediately, there isn't much we can do. Maybe there is a switch to make the call blocking?

**Comment by TekSiDoT** [comment]
Makes sense, I'll check it out on the VSC side, thanks!

**Comment by mantoni** [comment]
I found it here: https://code.visualstudio.com/docs/editor/codebasics#_additional-command-line-arguments

The option you're looking for is `-w` or `--wait`. You can this flag to the `$EDITOR` variable to cause VSC to wait before returning.

**Comment by TekSiDoT** [comment]
Excellent, thank you!
